# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='TITLE')),
                ('abstract', models.CharField(max_length=256, verbose_name='ABSTRACT')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('author', models.CharField(max_length=32, verbose_name='AUTHOR')),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('click', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='NAME')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
    ]
